version: '2.1'
services:
  kafka:
    #image: daggerok/kafka:spring-cloud-cli-v24
    #image: daggerok/kafka:v24
    image: daggerok/kafka:v10
    restart: unless-stopped
    environment:
      ZOOKEEPER_PORT: 2181
      KAFKA_PORT: 9092
      KAFKA_TOPICS: orders
      HTTP_PORT: 8080
    ports:
    - '2181:2181'
    - '9092:9092'
    networks:
      backing-services:
        aliases:
        - k
        - kafka
        - kafka.daggerok.com
  order-command:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./apps/order/command
      dockerfile: gradle/Dockerfile
    restart: unless-stopped
    ports:
    - '5006:5005'
    - '8081:8080'
    networks:
      backing-services:
        aliases:
        - oc
        - order-command
        - order-command.daggerok.com
#  order-query:
#    depends_on:
#      kafka:
#        condition: service_healthy
#    build:
#      context: ./apps/order/query
#      dockerfile: gradle/Dockerfile
#    restart: unless-stopped
#    ports:
#    - '5005:5005'
#    - '8082:8080'
#    networks:
#      backing-services:
#        aliases:
#        - oq
#        - order-query
#        - order-query.daggerok.com
#  inventory-order-items-reservation:
#    depends_on:
#      kafka:
#        condition: service_healthy
#    build:
#      context: ./apps/inventory/order-items-reservation
#      dockerfile: gradle/Dockerfile
#    ports: ['8083:8080']
#    networks:
#      backing-services:
#        aliases:
#        - io
#        - inventory-order-items-reservation
#        - inventory-order-items-reservation.daggerok.com
#  inventory-shipment:
#    depends_on:
#      kafka:
#        condition: service_healthy
#    build:
#      context: ./apps/inventory/shipment
#      dockerfile: gradle/Dockerfile
#    ports: ['8084:8080']
#    #mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)
#    networks:
#      backing-services:
#        aliases:
#        - is
#        - inventory-shipment
#        - inventory-shipment.daggerok.com
networks:
  backing-services:
    driver: bridge
