version: '2.1'
services:
  kafka:
    image: daggerok/kafka:spring-cloud-cli
    restart: unless-stopped
    environment:
      ZOOKEEPER_PORT: 2181
      KAFKA_PORT: 9092
    ports:
    - '2181:2181'
    - '9092:9092'
    volumes: ['kafka-data:/root']
    networks:
      backing-services:
        aliases:
        - k
        - kafka
        - kafka.daggerok.com
  order-command:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./order/command
      dockerfile: gradle/Dockerfile
    restart: unless-stopped
    volumes: ['order-command-data:/home']
    ports: ['8081:8080']
    networks:
      backing-services:
        aliases:
        - oc
        - order-command
        - order-command.daggerok.com
  order-query:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./order/query
      dockerfile: gradle/Dockerfile
    restart: unless-stopped
    volumes: ['order-query-data:/home']
    ports: ['8082:8080']
    networks:
      backing-services:
        aliases:
        - oq
        - order-query
        - order-query.daggerok.com
  inventory-order-items-reservation:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./inventory/order-items-reservation
      dockerfile: gradle/Dockerfile
    volumes: ['inventory-order-items-reservation-data:/home/']
    ports: ['8083:8080']
    networks:
      backing-services:
        aliases:
        - io
        - inventory-order-items-reservation
        - inventory-order-items-reservation.daggerok.com
  inventory-shipment:
    depends_on:
      kafka:
        condition: service_healthy
    build:
      context: ./inventory/shipment
      dockerfile: gradle/Dockerfile
    volumes: ['inventory-shipment-data:/home/']
    ports: ['8084:8080']
    #mem_limit: 209715200 # container limit: 200Mb (200 * 1024 * 1024)
    networks:
      backing-services:
        aliases:
        - is
        - inventory-shipment
        - inventory-shipment.daggerok.com
volumes:
  kafka-data: {}
  order-command-data: {}
  order-query-data: {}
  inventory-order-items-reservation-data: {}
  inventory-shipment-data: {}
networks:
  backing-services:
    driver: bridge
